"""init tables

Revision ID: ac5b21e0e31f
Revises: 
Create Date: 2025-09-24 22:43:22.821012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac5b21e0e31f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_index', sa.Integer(), nullable=False, comment='External bot ID managed by user'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bot_bot_index', 'bots', ['bot_index'], unique=False)
    op.create_index('idx_bot_created_at', 'bots', ['created_at'], unique=False)
    op.create_index(op.f('ix_bots_bot_index'), 'bots', ['bot_index'], unique=True)
    op.create_index(op.f('ix_bots_created_at'), 'bots', ['created_at'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evaluation_conversation_id', 'evaluations', ['conversation_id'], unique=False)
    op.create_index('idx_evaluation_created_at', 'evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluations_conversation_id'), 'evaluations', ['conversation_id'], unique=True)
    op.create_table('bot_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_index', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('knowledge_base', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_index'], ['bots.bot_index'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bot_version_bot_index', 'bot_versions', ['bot_index'], unique=False)
    op.create_index('idx_bot_version_created_at', 'bot_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_versions_bot_index'), 'bot_versions', ['bot_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_versions_bot_index'), table_name='bot_versions')
    op.drop_index('idx_bot_version_created_at', table_name='bot_versions')
    op.drop_index('idx_bot_version_bot_index', table_name='bot_versions')
    op.drop_table('bot_versions')
    op.drop_index(op.f('ix_evaluations_conversation_id'), table_name='evaluations')
    op.drop_index('idx_evaluation_created_at', table_name='evaluations')
    op.drop_index('idx_evaluation_conversation_id', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_bots_created_at'), table_name='bots')
    op.drop_index(op.f('ix_bots_bot_index'), table_name='bots')
    op.drop_index('idx_bot_created_at', table_name='bots')
    op.drop_index('idx_bot_bot_index', table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
